# **Introduction to Numpy**
  
  by : Hanindhiya Ika Septiana
  
---

**Contents:**
  *   Creating Numpy Array
  *   Matrix Operation
  *   Indexing, Slicing dan Iterasi Array
  *   Array Reshapping
  *   Joining Array
  *   List item



In [ ]:
!pip install numpy

In [ ]:
import numpy as np 

### **Creating Numpy Array**

In [ ]:
# 1D Array 
# axis 0 = 1,2,3 dan 4 (kesamping)
arr1 = np.array([1,2,3,4])
print("Dimension:", arr1.ndim)
arr1

Dimension: 1


array([1, 2, 3, 4])

In [ ]:
# 1D Array 
arr1 = np.array([1.5, 2.5, 3.5, 4.5])
print("Dimension:", arr1.ndim)
arr1

Dimension: 1


array([1.5, 2.5, 3.5, 4.5])

In [ ]:
# 1D Array - Vector with Range 
arr_1 = np.arange(1,10,1)
arr_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 2D Array 
# axis 0 = 1 dan 5 (kebawah) // axis 1 = 1,2,3 dan 4 (kesamping)
arr2 = np.array([[1,2,3,4], [5,6,7,8]])
print("Dimension:", arr2.ndim)
arr2

Dimension: 2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# 3D Array 
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print("Dimension:", arr3.ndim)
arr3

Dimension: 3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# Array + 1
arr4 = np.array( [ (1,2,3), (4,5,6)] )
print(arr4 + 1)

[[2 3 4]
 [5 6 7]]


In [ ]:
# Matrix with 0
arr5 = np.zeros(6)
arr5

array([0., 0., 0., 0., 0., 0.])

In [ ]:
# Matrix with 1 
arr6 = np.ones((6,6))
arr6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
# Matrix with Identity
m1 = np.identity(5)
m1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# HOMEWORK - Introduction to Numpy 
# Buatlah matrix 2 dimensi dengan nilai 1 - 30
arr_hw = np.array([[1,2,3,4,5,6], 
                  [7,8,9,10,11,12],
                  [13,14,15,16,17,18],
                  [19,20,21,22,23,24],
                  [25,26,27,28,29,30]])
print("Dimension:", arr_hw.ndim)
arr_hw

Dimension: 2


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
# HOMEWORK - Introduction to Numpy 
# Coding dan ambil angka 2,8,14,20,26

arr_hw[0:,1]

array([ 2,  8, 14, 20, 26])

In [ ]:
# HOMEWORK - Introduction to Numpy 
# Coding dan ambil angka 2,3,4,5,6 
arr_hw[0,1:]

array([2, 3, 4, 5, 6])

In [ ]:
# HOMEWORK - Introduction to Numpy 
# Coding dan ambil angka 23,24,29,30
arr_hw[3:,4:]

array([[23, 24],
       [29, 30]])

### **Matrix Operation**

In [ ]:
# 1D Matrix operation
# Elementwise Operation
# Penjumlahan 
anp = np.array([1,2,3,4,5])
bnp = np.array([6,7,8,9,10])

hasil = anp + bnp
hasil

array([ 7,  9, 11, 13, 15])

In [ ]:
# 1D Matrix operation
# Elementwise Operation
# Penjumlahan 
anp = np.array([1,2,3,4,5])
bnp = np.array([6,7,8,9,10])

np.add(anp,bnp)

array([ 7,  9, 11, 13, 15])

In [ ]:
# Elementwise Operation
# Pengurangan
anp = np.array([1,2,3,4,5])
bnp = np.array([6,7,8,9,10])

hasil = anp - bnp
hasil

array([-5, -5, -5, -5, -5])

In [ ]:
# Elementwise Operation
# Perkalian
anp = np.array([1,2,3,4,5])
bnp = np.array([6,7,8,9,10])

hasil = anp * bnp
hasil

array([ 6, 14, 24, 36, 50])

In [ ]:
# Elementwise Operation
# Pembagian
anp = np.array([1,2,3,4,5])
bnp = np.array([6,7,8,9,10])

hasil = anp / bnp
hasil

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
# Perkalian Matriks
# 2D Array x 2D Array
arr1 = np.array([[1,2],
                [3,4]])
arr2 = np.ones([2,2])

hasil = np.dot(arr1,arr2)
print('Hasil Perkalian Matriks 2D x 2D')
print(hasil)

Hasil Perkalian Matriks 2D x 2D
[[3. 3.]
 [7. 7.]]


In [ ]:
# Perkalian Matriks
# 2D Array x 3D Array
arr3 = np.array([[1,2,3],
                 [4,0,1]])
arr4 = np.array([[1,2],
                  [3,1],
                  [-1,2]])

hasil = np.dot(arr3,arr4)
print('Hasil Perkalian Matriks 2D x 3D')
print(hasil)

Hasil Perkalian Matriks 2D x 3D
[[ 4 10]
 [ 3 10]]


### **Indexing, Slicing dan Iterasi Array**

In [ ]:
# Indexing
#Get the number 1 from array
arr1 = np.array([1,2,3,4])
arr1[0]

1

In [ ]:
# Indexing
# get the last 2 data in array
arr1 [-2:]

array([3, 4])

In [ ]:
# Slicing
# get the second index from the second array
arr2 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 [1,1] #[start,end]

6

In [ ]:
# Iterasi
a = np.arange(10)**2

for i in a:
  print('Value =', i)

Value = 0
Value = 1
Value = 4
Value = 9
Value = 16
Value = 25
Value = 36
Value = 49
Value = 64
Value = 81


### **Array Reshaping** 

In [ ]:
# Transpose 
a = np.array(([1,2,3],
              [4,5,6]))
print('Tampilkan Matriks a dengan ukuran', a.shape)
print(a)

print('Tampilkan Matriks a yang sudah ditranspose')
print(a.transpose())

Tampilkan Matriks a dengan ukuran (2, 3)
[[1 2 3]
 [4 5 6]]
Tampilkan Matriks a yang sudah ditranspose
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
array_b = np.array([i for i in range(20)])
array_b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# Reshape from 1D to 2D
array_b.reshape(4,5) #Having 4 array with 5 elements

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# Reshape from 1D to 3D
D_3D = array_b.reshape(2,2,5)
display(D_3D)

print("Dimension:",D_3D.shape) # Having 2 arrays that contain 2 array with 5 elements

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

Dimension: (2, 2, 5)


### **Join & Split**

In [ ]:
# concatenate -1D
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,11,12,13,14])

concat1 = np.concatenate((arr1,arr2), axis=0)
concat1

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [ ]:
# concatenate - 2D
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[10,11,12],[13,14,15]])

concat2 = np.concatenate((arr3,arr4), axis=1)
concat2

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15]])

In [ ]:
# split
split_1 = np.array_split(concat1,2,axis=0)

display(split_1)

print("First array:", split_1[0])
print("Second array:", split_1[1])

[array([1, 2, 3, 4, 5]), array([10, 11, 12, 13, 14])]

First array: [1 2 3 4 5]
Second array: [10 11 12 13 14]


In [ ]:
# split
split_2 = np.array_split(concat2,2,axis=1)

display(split_2)

print("First array:")
print(split_2[0])

print("Second array:")
print(split_2[1])

[array([[1, 2, 3],
        [4, 5, 6]]), array([[10, 11, 12],
        [13, 14, 15]])]

First array:
[[1 2 3]
 [4 5 6]]
Second array:
[[10 11 12]
 [13 14 15]]
